What is NumPy?
--------------
1. NumPy stands for Numerical Python.
2. NumPy is a Python library used for working with arrays.
3. It also has functions for working in domain of linear algebra, fourier transform, and matrices.

Why Use NumPy?
--------------
1. In Python we have lists that serve the purpose of arrays, but they are slow to process.
2. NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
3. The array object in NumPy is called ndarray

Why is NumPy Faster Than Lists?
-------------------------------
1. NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

In [2]:
import numpy as np

In [6]:
# Convert List to Single Dimention Array

list01 = [10, 20, 30, 40]

print(list01, type(list01))

print('----------------------------------------------------------------------')

numpyList01 = np.array(list01)

print(numpyList01, type(numpyList01))

[10, 20, 30, 40] <class 'list'>
----------------------------------------------------------------------
[10 20 30 40] <class 'numpy.ndarray'>


In [7]:
# Convert List to Two Dimention Array

list01 = [[10, 20], [30, 40]]

print(list01, type(list01))

print('----------------------------------------------------------------------')

numpyList01 = numpy.array(list01)

print(numpyList01, type(numpyList01))

[[10, 20], [30, 40]] <class 'list'>
----------------------------------------------------------------------
[[10 20]
 [30 40]] <class 'numpy.ndarray'>


In [13]:
# Convert List to Multi Dimention Array

list01 = [[10, 20], [30, 40], [50, 60], [70, 80]]

print(list01, type(list01))

print('----------------------------------------------------------------------')

numpyList01 = numpy.array(list01)

print(numpyList01, type(numpyList01))

[[10, 20], [30, 40], [50, 60], [70, 80]] <class 'list'>
----------------------------------------------------------------------
[[10 20]
 [30 40]
 [50 60]
 [70 80]] <class 'numpy.ndarray'>


Arange :
--------
1. Return evenly spaced values within a given interval.

In [15]:
import numpy as np

In [16]:
a = np.arange(0,10)

print(a, type(a))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [17]:
a = np.arange(0, 10, 2)

print(a, type(a))

[0 2 4 6 8] <class 'numpy.ndarray'>


In [18]:
a = np.arange(1, 10, 2)

print(a, type(a))

[1 3 5 7 9] <class 'numpy.ndarray'>


Linspace :
----------
1. Return evenly spaced numbers over a specified interval.

In [21]:
print(np.arange(0,10,3))

print('----------------------------------------')

print(np.linspace(0,10,3))

[0 3 6 9]
----------------------------------------
[ 0.  5. 10.]


In [23]:
print(np.arange(0,20,3))

print('----------------------------------------')

print(np.linspace(0,20,3))

print(np.linspace(0,20,5))

[ 0  3  6  9 12 15 18]
----------------------------------------
[ 0. 10. 20.]
[ 0.  5. 10. 15. 20.]


In [26]:

a = np.linspace(0, 50, 5)

print(a)

print('----------------------------------------')

a = np.linspace(0, 50, 5, dtype=int,)

print(a)

[ 0.  12.5 25.  37.5 50. ]
----------------------------------------
[ 0 12 25 37 50]


Random :
--------
Numpy also has lots of ways to create random number arrays:

Randint :
---------    
Return random integers from low (inclusive) to high (exclusive).

In [4]:
import numpy as np

np.random.randint(1,100)

71

In [5]:
a = np.random.randint(1,100,10)

print(a)

[25 38 94 81 43 40 20 49 19 11]


Array Attributes and Methods:
-----------------------------

In [11]:
arr = np.arange(25)

randarr = np.random.randint(0,50,6)

print(arr)

print('-----------------------------------------------')

print(randarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
-----------------------------------------------
[13 15 48 32 28 49]


01 Reshape :
------------    
Returns an array containing the same data with a new shape.

In [12]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [13]:
randarr.reshape(3, 2)

array([[13, 15],
       [48, 32],
       [28, 49]], dtype=int32)

In [14]:
randarr.reshape(2, 3)

array([[13, 15, 48],
       [32, 28, 49]], dtype=int32)

Shape:
------
Shape is an attribute that arrays have (not a method):

In [16]:
list01 = [[10, 20], [30, 40], [50, 60]]

print(list01, type(list01))

print('----------------------------------------------------------------------')

numpyList01 = np.array(list01)

print(numpyList01, type(numpyList01))

[[10, 20], [30, 40], [50, 60]] <class 'list'>
----------------------------------------------------------------------
[[10 20]
 [30 40]
 [50 60]] <class 'numpy.ndarray'>


In [17]:
'''
(3, 2) = (number of rows, number of columns)
'''

numpyList01.shape

(3, 2)

In [18]:
print(numpyList01)

print('----------------------------------------------------------------------')

ex01 = numpyList01.reshape(2, 3)

print(ex01)

[[10 20]
 [30 40]
 [50 60]]
----------------------------------------------------------------------
[[10 20 30]
 [40 50 60]]


max,min,argmax,argmin
---------------------
These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [20]:
ranarr = np.random.randint(0,50,10)

print(ranarr)

[10 29 35 12 35 29 37 48 34 46]


In [21]:
# To find the Maximum value 

print(ranarr.max())

48


In [22]:
# To find the Minimum value 

minValue = ranarr.min()

print(minValue)

10


In [23]:
# To find the Maximum value position

print(ranarr.argmax())

7


In [24]:
# To find the Minimum value position

print(ranarr.argmin())

0


NumPy Indexing and Selection :
------------------------------

In [26]:
#Creating sample array

arr = np.array([10,20,30,40,50,60,70,80,90,100])

print(arr)

[ 10  20  30  40  50  60  70  80  90 100]


In [27]:
#Get a value at an index

print(arr[8])

90


In [28]:
#Get values in a range

arr[1:5]

array([20, 30, 40, 50])

In [29]:
#Setting a value with index range (Broadcasting)

arr[0:5] = 200

#Show
arr

array([200, 200, 200, 200, 200,  60,  70,  80,  90, 100])

Now note the changes also occur in our original array! :

In [30]:
print(arr)

[200 200 200 200 200  60  70  80  90 100]


Data is not copied, it's a view of the original array! This avoids memory problems! :
-------------------------------------------------------------------------------------
In NumPy, when you slice or subset an array, it doesn’t create a new array but instead creates a "view" of the original data. 
This means that if you modify the view, it will also affect the original array, avoiding extra memory usage.

In [31]:
#To get a copy, need to be explicit

arr_copy = arr.copy()

print(arr_copy)

[200 200 200 200 200  60  70  80  90 100]


In [32]:
arr_copy[2:5] = 250

#Show
arr_copy

array([200, 200, 250, 250, 250,  60,  70,  80,  90, 100])

In [33]:
print(arr)

[200 200 200 200 200  60  70  80  90 100]


Indexing and slicing a multi Dimention array (matrices) :
---------------------------------------------------------
The general format is arr_2d[row][col] or arr_2d[row,col]. I recommend usually using the comma notation for clarity.

In [39]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d



array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [36]:
#Indexing row

arr_2d[1]

array([20, 25, 30])

In [37]:
#Indexing Column

print(arr_2d[0:3,0])

[ 5 20 35]


In [40]:
# Get a Single value

print(arr_2d[0][1])

10
