In [1]:
import numpy as np

Broadcasting :
--------------

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.

In [8]:
v1 = [10, 20, 30]

print(v1, type(v1))

print('------------------------------------------')

nv1 = np.array(v1)

print(nv1)

print('------------------------------------------')

print(nv1 * 2)

[10, 20, 30] <class 'list'>
------------------------------------------
[10 20 30]
------------------------------------------
[20 40 60]


In [11]:
nv1 = np.array([1, 2, 3, 4])

nv2 = np.array([1, 2, 3, 4])

print(nv1, ' + ' ,nv2, ' = ', nv1 + nv2)

[1 2 3 4]  +  [1 2 3 4]  =  [2 4 6 8]


In [29]:
nv1 = np.array([1, 2, 3, 4])

nv2 = np.array([1, 2, 3, 4])

print(nv1)

print(nv2)

print('------------------------------------------')

rnv21 = nv2.reshape(4, 1)

print(rnv21)

print(nv1 * rnv21)

print('------------------------------------------')

rnv21 = nv2.reshape(2, 2)

print(rnv21)

print('------------------------------------------')

print(2 * rnv21)

[1 2 3 4]
[1 2 3 4]
------------------------------------------
[[1]
 [2]
 [3]
 [4]]
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]
------------------------------------------
[[1 2]
 [3 4]]
------------------------------------------
[[2 4]
 [6 8]]


In [32]:
arr = np.array([[1, 2], [3, 4], [5, 6]])

print('-----------------------------------------------')

print(arr)

print('-----------------------------------------------')

print('Sum along columns : ', np.sum(arr, axis=0))  
print('Sum along rows : ', np.sum(arr, axis=1)) 

-----------------------------------------------
[[1 2]
 [3 4]
 [5 6]]
-----------------------------------------------
Sum along columns :  [ 9 12]
Sum along rows :  [ 3  7 11]


Selection:
----------
Let's briefly go over how to use brackets for selection based off of comparison operators.

In [38]:
arr = np.array([10,20,30,40,50,60,70,80,90,100])

print(arr)

[ 10  20  30  40  50  60  70  80  90 100]


In [42]:
print(arr > 40)

[False False False False  True  True  True  True  True  True]


In [43]:
bool_arr = arr > 40

print(arr[bool_arr])

[ 50  60  70  80  90 100]
