NumPy Operations
----------------
Arithmetic
----------
You can easily perform array with array arithmetic, or scalar with array arithmetic.

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,10)

print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
# arr2 = [0 1 2 3 4 5 6 7 8 9] + [0 1 2 3 4 5 6 7 8 9]

arr2 = arr + arr

print(arr2)

[ 0  2  4  6  8 10 12 14 16 18]


In [7]:
arr2 = arr - arr

print(arr2)

[0 0 0 0 0 0 0 0 0 0]


Python Numpy Read and Write Text Files:
---------------------------------------

In [15]:
x = np.array([[1,2,3], [4,5,6],[7,8,9]], np.int32)

print(x)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
# Create txt File

np.savetxt("test.txt", x)

In [17]:
# Read txt File

y = np.loadtxt('test.txt')

print(y)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
